# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inspect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inspect.proto',
  package='inspect',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rinspect.proto\x12\x07inspect\"\x1d\n\x0eInspectRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\" \n\x0cInspectReply\x12\x10\n\x08\x63\x61nfetch\x18\x01 \x01(\x08\x32\x44\n\x07Inspect\x12\x39\n\x07Inspect\x12\x17.inspect.InspectRequest\x1a\x15.inspect.InspectReplyb\x06proto3'
)




_INSPECTREQUEST = _descriptor.Descriptor(
  name='InspectRequest',
  full_name='inspect.InspectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='inspect.InspectRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=55,
)


_INSPECTREPLY = _descriptor.Descriptor(
  name='InspectReply',
  full_name='inspect.InspectReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='canfetch', full_name='inspect.InspectReply.canfetch', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['InspectRequest'] = _INSPECTREQUEST
DESCRIPTOR.message_types_by_name['InspectReply'] = _INSPECTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InspectRequest = _reflection.GeneratedProtocolMessageType('InspectRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSPECTREQUEST,
  '__module__' : 'inspect_pb2'
  # @@protoc_insertion_point(class_scope:inspect.InspectRequest)
  })
_sym_db.RegisterMessage(InspectRequest)

InspectReply = _reflection.GeneratedProtocolMessageType('InspectReply', (_message.Message,), {
  'DESCRIPTOR' : _INSPECTREPLY,
  '__module__' : 'inspect_pb2'
  # @@protoc_insertion_point(class_scope:inspect.InspectReply)
  })
_sym_db.RegisterMessage(InspectReply)



_INSPECT = _descriptor.ServiceDescriptor(
  name='Inspect',
  full_name='inspect.Inspect',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=91,
  serialized_end=159,
  methods=[
  _descriptor.MethodDescriptor(
    name='Inspect',
    full_name='inspect.Inspect.Inspect',
    index=0,
    containing_service=None,
    input_type=_INSPECTREQUEST,
    output_type=_INSPECTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INSPECT)

DESCRIPTOR.services_by_name['Inspect'] = _INSPECT

# @@protoc_insertion_point(module_scope)
