# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inspect_pb2 as inspect__pb2


class InspectStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inspect = channel.unary_unary(
                '/inspect.Inspect/Inspect',
                request_serializer=inspect__pb2.InspectRequest.SerializeToString,
                response_deserializer=inspect__pb2.InspectReply.FromString,
                )


class InspectServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InspectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=inspect__pb2.InspectRequest.FromString,
                    response_serializer=inspect__pb2.InspectReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inspect.Inspect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Inspect(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inspect.Inspect/Inspect',
            inspect__pb2.InspectRequest.SerializeToString,
            inspect__pb2.InspectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
